// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	ProtoError
	MessageReq
	MessageRep
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 消息类型
type MessageType int32

const (
	// 未知
	MessageType_MT_NONE MessageType = 0
	// 推送
	MessageType_MT_PUSH MessageType = 1
	// 短信
	MessageType_MT_SMS MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "MT_NONE",
	1: "MT_PUSH",
	2: "MT_SMS",
}
var MessageType_value = map[string]int32{
	"MT_NONE": 0,
	"MT_PUSH": 1,
	"MT_SMS":  2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 错误返回
type ProtoError struct {
	// 错误代码
	Code int32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	// 错误信息
	Error string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	// 错误位置
	File string `protobuf:"bytes,3,opt,name=file" json:"file,omitempty"`
}

func (m *ProtoError) Reset()                    { *m = ProtoError{} }
func (m *ProtoError) String() string            { return proto.CompactTextString(m) }
func (*ProtoError) ProtoMessage()               {}
func (*ProtoError) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MessageReq struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *MessageReq) Reset()                    { *m = MessageReq{} }
func (m *MessageReq) String() string            { return proto.CompactTextString(m) }
func (*MessageReq) ProtoMessage()               {}
func (*MessageReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MessageRep struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Count int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *MessageRep) Reset()                    { *m = MessageRep{} }
func (m *MessageRep) String() string            { return proto.CompactTextString(m) }
func (*MessageRep) ProtoMessage()               {}
func (*MessageRep) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*ProtoError)(nil), "main.ProtoError")
	proto.RegisterType((*MessageReq)(nil), "main.MessageReq")
	proto.RegisterType((*MessageRep)(nil), "main.MessageRep")
	proto.RegisterEnum("main.MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xc9, 0x4d, 0xcc, 0xcc, 0x53, 0xf2, 0xe2, 0xe2,
	0x0a, 0x00, 0x71, 0x5d, 0x8b, 0x8a, 0xf2, 0x8b, 0x84, 0x84, 0xb8, 0x58, 0x92, 0xf3, 0x53, 0x52,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xc0, 0x6c, 0x21, 0x11, 0x2e, 0xd6, 0x54, 0x90, 0xa4,
	0x04, 0x93, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0x03, 0x52, 0x99, 0x96, 0x99, 0x93, 0x2a, 0xc1,
	0x0c, 0x16, 0x04, 0xb3, 0x95, 0x8c, 0xb8, 0xb8, 0x7c, 0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0x83,
	0x52, 0x0b, 0x85, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0xc0, 0x26, 0x71, 0x06, 0x31, 0x65, 0xa6, 0x80,
	0xcc, 0x49, 0xce, 0x2f, 0xcd, 0x2b, 0x01, 0x9b, 0xc3, 0x1a, 0x04, 0xe1, 0xa0, 0xe8, 0x29, 0x20,
	0x4e, 0x8f, 0x96, 0x31, 0x17, 0x37, 0x54, 0x4f, 0x48, 0x65, 0x41, 0xaa, 0x10, 0x37, 0x17, 0xbb,
	0x6f, 0x48, 0xbc, 0x9f, 0xbf, 0x9f, 0xab, 0x00, 0x03, 0x94, 0x13, 0x10, 0x1a, 0xec, 0x21, 0xc0,
	0x28, 0xc4, 0xc5, 0xc5, 0xe6, 0x1b, 0x12, 0x1f, 0xec, 0x1b, 0x2c, 0xc0, 0x94, 0xc4, 0x06, 0xf6,
	0xb5, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x0f, 0x83, 0xe3, 0x03, 0x01, 0x00, 0x00,
}
